### ISSUE TITLE
Mth recursive method is causing CPU load problems

### ISSUE THREAD

**Issue by mmeloni** [codenotary/merkletree#1]
During verifications https://github.com/codenotary/merkletree/blob/master/tree.go#L122 is called an huge amount of times causing CPU load problems

**Comment by leogr** [comment]
`mth` should be called only when [notes in the path are not frozen](https://github.com/codenotary/merkletree/blob/master/tree.go#L177). How many time it is being called per proof checking? Do you have any metrics?

Furthermore, it can be refactored to a non-recursive implementation that would slightly improve performance though it won't change the computational complexity.

**Comment by mmeloni** [comment]
In a DB with 3514367 entries is called 2834429 times during inclusion.
I noticed also  that in https://github.com/codenotary/merkletree/blob/master/mth_test.go#L28 is called 4226 times.

**Comment by leogr** [comment]
Since 3514367 < 2834429, I assume that not all entries were tested or it's not called at least one-time per entry.

`TestMTH` is testing a different function but the same algorithm. Anyway `4226` is perfectly fine in that case, since:
- 1 time is called with and empty tree
- 64 times where each recursion is equal to the 2 times the sum of the level, so sum(2n) n=0 to 64

That's exactly 1 + 64 + [sum(2n) n=0 to 64] = 4226

Reimplementing it in a non-recursive fashion will reduce the function calls just to 65 (in this case).

So it makes sense iff the CPU time is wasted by the function calls. Could you confirm this?
